#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Deletes a tag, both locally and on the remote origin.
#
# Usage:
#   git deltag {tag}
##

tag="$1"

if [[ -z "${tag}" ]]; then
    echo "Tag name is required." >&2
    exit 1
fi

git tag -d "${tag}"
git push --delete origin "${tag}"
