#! /usr/bin/env bash
# Copyright (c) 2023-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# The hash for the creation of the repository, before the first commit.
#
# Usage:
#   git first
##

git rev-list --max-parents=0 HEAD
