#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Unstage any files which have been added to be committed.
#
# Usage:
#   git unstage
##

git reset HEAD
