#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# `git lola` is a standard version of `git log`. It uses the long commit ID,
# commit message, commit author, and relative timestamp.
#
# It also uses `--graph` to show branch relationships.
#
# Usage:
#   git lola
##

git log --graph --decorate \
    --pretty=format:'%C(red)%H%C(reset) %C(yellow)%d%C(reset) %s [%C(green)%an <%aE>, %C(bold black)%ai%C(reset)]' \
    --abbrev-commit --date=relative --all --no-merges "$@"
