#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Undo the most recent commit.
#
# Usage:
#   git uncommit
##

git reset --soft HEAD^
