#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# The inverse of `cherry-pick`. Removes a single commit from a branch. Requires
# a force-push to the remote.
#
# Usage:
#   git cherry-pit {commit}
#
# https://sethrobertson.github.io/GitFixUm/fixup.html#remove_deep
##

echo "This process can be potentially devastating. See https://flwd.dk/3fQHmsA for gotchas."
echo "---------------------------------------------------------------------"
# shellcheck disable=SC2034,SC2162
read -p "Press any key to continue, or press Control+C to cancel. " x

git rebase -p --onto "$1^" "$1"
