#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Returns the name of the current branch, WITHOUT a trailing linebreak.
# Useful for copy-pasting into subsequent commands.
#
# Usage:
#   git this
##

current_branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ -z "${current_branch}" ]]; then
    echo "You do not appear to be on a branch." >&2
    exit 1
fi

echo -n "${current_branch}"
