#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Gets the short version of a commit ID.
#
# Usage:
#   git short e60a01d107d0de7f97689bb311d8d8d80862e583
#   => e60a01d
##

git log --pretty=format:'%h' -n 1 "$@"
