#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Finds which branches/tags a particular commit is part of.
#
# Usage:
#   git contains {hash}
##

git branch -a --contains "$@"
