#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Gets the short form of the current commit hash, WITHOUT a trailing linebreak.
# Useful for copy-pasting into subsequent commands.
#
# Usage:
#   git cm
##

shortlog="$(git log --pretty=format:'%h' -n 1)"
echo -n "${shortlog}"
