#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Permanently blows-away any uncommitted changes. Resets to the position of the
# last commit. Goal is to reset the repo to the last pristine state.
#
# Usage:
#   git nuke
##

git reset --hard HEAD
