#! /usr/bin/env bash
# Copyright (c) 2014-2021 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Returns the GitHub (et al) owner/repository pattern for the current branch's
# remote SSH URL. It doesn't make sense to use this with remotes that are not
# SSH or follow the GitHub style.
#
# Usage:
#   git remote-repo <remote>
#   git remote-repo `git remotes`
##

remote_name="$1"

# Get the URL.
repo_url="$(git remote get-url "${remote_name}")"

# Strip the username and host from the URL.
repo_url="$(echo -n "${repo_url}" | sed -e "s,.*:,,")"

# Strip the trailing `.git` from the URL.
repo_url="$(echo -n "${repo_url}" | sed -e "s/\.git$//")"

echo "${repo_url}"
