#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# `git hist` is a standard version of `git log`. It uses the long commit ID,
# commit message, commit author, and relative timestamp.
#
# It also includes a list of all files that were changed in that commit.
#
# Usage:
#   git hist
##

git log --color --decorate \
    --pretty=format:'%C(red)%H%C(reset) %C(yellow)%d%C(reset) %s [%C(green)%an, %C(bold black)%cr%C(reset)]' \
    --stat --abbrev-commit --date=relative --all
