#! /usr/bin/env bash
# Copyright (c) 2018-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Opens the website for the current Git branch. Works for GitHub, GitHub
# Enterprise, GitLab, and BitBucket. When it can't figure out what else to do,
# it assumes a GitHub-compatible URL pattern.
#
# Usage:
#   git open
#   git open <remote>
#   git open <remote> <branch>
##

# If not specified at runtime, apply default values (remote: origin; branch: current)
remote=${1:-origin}
branch=${2:-$(git rev-parse --abbrev-ref HEAD)}

# Get the URL for the remote.
base_url="$(git remote get-url "${remote}")"

# If this is already an HTTPS remote URL, use it as-is.
if echo "${base_url}" | grep -Eqe "^(git\+)?http"; then
    base_url="${base_url#git+}"

    if hash open 2>/dev/null; then
        open "${base_url}"
    else
        echo "${base_url}"
    fi

    exit 0
fi

# Assume an SSH URL.
# macOS/BSD sed does not support non-greedy modifiers, but this is probably fine.
base_url_pieces="$(echo "${base_url}" | sed -Ee 's,^([^@]+)@([^:]+):(.*)$,\1 \2 \3,')"
hostname="$(echo -n "${base_url_pieces}" | awk '{print $2}')"
path="$(echo -n "${base_url_pieces}" | awk '{print $3}')"
path="${path%.git}"

# Works for GitHub.com, GitHub Enterprise, and GitLab.org. Treat as default.
git_url="https://${hostname}/${path}/tree/${branch}"

# BitBucket uses 'src' instead of 'tree'.
if [[ "${hostname}" == *bitbucket* ]]; then
    git_url="https://${hostname}/${path}/src/${branch}"
fi

if hash open 2>/dev/null; then
    open "${git_url}"
else
    echo "${git_url}"
fi
