#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Displays an interactive list of all tags in the repository. Making a selection
# from the interactive prompt will pass the name of the tag to the next step.
#
# Requires `fzf` and `tmux`.
#   brew install fzf tmux
#
# Usage:
#   git tags
##

tags="$(git tag --sort -version:refname)"

echo "${tags}" | fzf-tmux \
    --multi \
    --preview-window right:70% \
    --preview 'git show --color=always {} | head -'"${LINES}"
