#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Shows the commits from the current branch which are not in the specified branch.
#
# Usage:
#   git delta <branch>
##

current_branch="$(git rev-parse --abbrev-ref HEAD)"
compared_branch="$1"

if [[ -z "${current_branch}" ]]; then
    echo "You do not appear to be on a branch." >&2
    exit 1
fi

if [[ -z "${compared_branch}" ]]; then
    echo "Branch name is required." >&2
    exit 1
fi

if [[ ${current_branch} == "${compared_branch}" ]]; then
    echo "You cannot compare a branch to itself." >&2
    exit 1
fi

results="$(git cherry -v "${compared_branch}" "${current_branch}")"
results="$(echo "${results}" | grep '^+')"
results="$(echo "${results}" | awk '{print $2}')"

echo "${results}" | xargs git show \
    --pretty=format:'%C(red)%H%C(reset) %C(yellow)%d%C(reset) %s [%C(green)%an, %C(bold black)%cr%C(reset)]' \
    --summary --no-patch --color --decorate --stat --abbrev-commit --date=relative
