#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Opens merge-conflicted files for editing in the editor you provide.
#
# Usage:
#   <editor> `git conflicted`
##

changed_files="$(git diff --name-only)"
uniq_changed_files="$(echo "${changed_files}" | uniq)"

if [[ -z "${uniq_changed_files}" ]]; then
    echo "No conflicted files found." >&2
    exit 1
fi

echo "${uniq_changed_files}"
