#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Gets the long form of the current commit hash, WITHOUT a trailing linebreak.
# Useful for copy-pasting into subsequent commands.
#
# Usage:
#   git cml
##

longlog="$(git log --pretty=format:'%H' -n 1)"
echo -n "${longlog}"
