#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# `git lola` is a standard version of `git log`. It uses the long commit ID,
# commit message, commit author, and relative timestamp.
#
# It also restricts the list of commits to only the current branch.
#
# Usage:
#   git lolc
##

current_branch="$(git rev-parse --abbrev-ref HEAD)"

git log --graph --decorate \
    --pretty=format:'%C(red)%H%C(reset) %C(yellow)%d%C(reset) %s [%C(green)%an, %C(bold black)%cr%C(reset)]' \
    --abbrev-commit --date=relative --first-parent "${current_branch}"
