#! /usr/bin/env bash
# written up by Jan Engelhardt, 2008
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the WTF Public License version 2 or
# (at your option) any later version.

##
# Configures the current branch to track the given upstream branch. Does not
# support branches with a `/` in its name.
#
# Usage:
#   git track <remote>/<branch>
##

current_branch="$(git rev-parse --abbrev-ref HEAD)"
remote="$1"

if [[ -z "${current_branch}" ]]; then
    echo "You do not seem to be on a branch." >&2
    exit 1
fi

# Grab the names before the / and after.
remote_name="${remote%/*}"
remote_branch="${remote#*/}"

# Update the git config.
git config "branch.${current_branch}.remote" "${remote_name}"
git config "branch.${current_branch}.merge" "${remote_branch}"
