#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Displays an interactive list of all branches in the repository. Making a
# selection from the interactive prompt will pass the name of the branch to the
# next step.
#
# Requires `fzf` and `tmux`.
#   brew install fzf tmux
#
# Usage:
#   git br
##

branches="$(
    git for-each-ref \
        --count=30 \
        --sort \
        -version:refname refs/heads/ \
        --format='%(refname:short)'
)"

echo "${branches}" | fzf-tmux \
    --multi \
    --preview-window right:70% \
    --preview 'git show --color=always {} | head -'"${LINES}"
