#! /usr/bin/env bash
# Copyright (c) 2014-2025 Ryan Parman <https://ryanparman.com>
# http://opensource.org/licenses/MIT

##
# Searches the git log for files which contain the given phrase.
#
# Usage:
#   git find "pdepend"
##

git log -S"$1" --decorate \
    --pretty=format:'%C(red)%H%C(reset) %C(yellow)%d%C(reset) %s [%C(green)%an, %G?, %C(bold black)%cI%C(reset)]' \
    --date=relative --all -p
